project_id = "tfiqamtyezkrhnfkdbuv"

[functions.ai-optimize-resume]
verify_jwt = false

[functions.ai-rate-answer]
verify_jwt = false

[functions.ai-cover-letter]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.ai-interviewer-research]
verify_jwt = false

[functions.ai-extract-keywords]
verify_jwt = false

[functions.ai-resume-versions]
verify_jwt = false

[functions.ai-job-match]
verify_jwt = false
